[
  {app_id=".arandr-wrapped";}
  {app_id=".virt-manager-wrapped";}
  {app_id="Waydroid";}
  {app_id="com.obsproject.Studio";}
  {app_id="deluge";}
  {app_id="electrum";}
  {app_id="file-roller";}
  {app_id="lutris";}
  {app_id="nemo";}
  {app_id="org.getmonero.monero-wallet-gui";}
  {app_id="org.gnome.Nautilus";}
  {app_id="org.kde.ark";}
  {app_id="org.kde.dolphin";}
  {app_id="org.kde.gwenview";}
  {app_id="radeon-profile";}
  {app_id="subl";}
  {app_id="thunderbird";}
  {app_id="transmission-gtk";}
  {app_id="xdg-desktop-portal";}
  {app_id="xdg-desktop-portal-gtk";}
  {app_id="zenity";}
  {class="Insomnia";}
  {class="Mario spel";}
  {class="Matplotlib"; }
  {class="Qemu-system-i386";}
  {class="Vlc";}
  {class="Week 39";}
  {class="bruno";}
  {class="code-oss";}
  {class="obs";}
  {class="steam";}
  {class="vlc";}
  {class="zoom";}
  {instance="Godot_ProjectList"; }
  {instance="Toolkit";}
  {instance="copilot.microsoft.com";}
  {instance="x.com__i_grok";}
  {title="Developer Tools —";}
  {window_role="pop-up";}
  {window_role="toolbox";}
]
