[
  {class="Vlc";}
  {class="vlc";}
  {app_id="mpv";}
  {class="feh";}
  {class="Insomnia";}
  {class="steam";}
  {class="Mario spel";}
  {class="code-oss";}
  {window_role="toolbox";}
  {window_role="pop-up";}
  {instance="Toolkit";}
  {app_id="org.kde.dolphin";}
  {app_id="org.gnome.Nautilus";}
  {app_id="com.obsproject.Studio";}
  {class="obs";}
  {app_id="subl";}
  {app_id="org.kde.gwenview";}
  {app_id="radeon-profile";}
  {app_id="org.kde.ark";}
  {app_id="deluge";}
  {app_id="electrum";}
  {app_id="org.getmonero.monero-wallet-gui";}
  {app_id="transmission-gtk";}
  {class="Week 39";}
  {class="zoom";}
  {app_id="Waydroid";}
  {app_id="lutris";}
  {app_id="zenity";}
  {class="Qemu-system-i386";}
  {title="Developer Tools —";}
  { instance = "Godot_ProjectList"; }
  { instance = "Godot_Engine"; }
  { class = "Godot"; }
  {app_id="xdg-desktop-portal-gtk";}
  {app_id="xdg-desktop-portal";}
  {app_id="nemo";}
  {app_id="file-roller";}
  { class="Matplotlib"; }
]
