#!/bin/bash
# This project is libre, and licenced under the terms of the
# DO WHAT THE FUCK YOU WANT TO PUBLIC LICENCE, version 3.1,
# as published by dtf on July 2019. See the LICENSE file or
# https://ph.dtf.wtf/w/wtfpl/#version-3-1 for more details.

# Displays the default device, volume, and mute status for i3blocks
# Required pkgs (voidlinux) are:
#	pipewire
#	pamixer
#	pulseaudio-utils

AUDIO_HIGHER_THRESH=80
AUDIO_HIGHER_COLOR="${PRIMARY_COLOR}"
AUDIO_HIGHEST_THRESH=90
AUDIO_HIGHEST_COLOR="#FF0000"

AUDIO_HIGH_SYMBOL=' '

AUDIO_MED_HIGH_THRESH=70
AUDIO_MED_HIGH_SYMBOL=' '

AUDIO_MED_THRESH=30
AUDIO_MED_SYMBOL=' '

AUDIO_LOW_THRESH=0
AUDIO_LOW_SYMBOL=' '

AUDIO_MUTED_SYMBOL=' '

AUDIO_INTERVAL=1

ICON_COLOR="${PRIMARY_COLOR}"
DEFAULT_COLOR="${FOREGROUND_COLOR}"
#DEFAULT_COLOR="#FFFFFF"
MUTED_COLOR="${THIRD_COLOR}"
#MUTED_COLOR="#a0a0a0"

LONG_FORMAT=1
SHORT_FORMAT=0
USE_PERCENT=1
USE_ALSA_NAME=0
USE_DESCRIPTION=1

while getopts F:f:pdH:M:L:X:T:t:C:c:i:h opt; do
	case "$opt" in
		F) LONG_FORMAT="$OPTARG" ;;
		f) SHORT_FORMAT="$OPTARG" ;;
		p) USE_PERCENT=0 ;;
		d) USE_DESCRIPTION=1 ;;
		H) AUDIO_HIGH_SYMBOL="$OPTARG" ;;
		M) AUDIO_MED_SYMBOL="$OPTARG" ;;
		L) AUDIO_LOW_SYMBOL="$OPTARG" ;;
		X) AUDIO_MUTED_SYMBOL="$OPTARG" ;;
		T) AUDIO_MED_THRESH="$OPTARG" ;;
		t) AUDIO_LOW_THRESH="$OPTARG" ;;
		C) DEFAULT_COLOR="$OPTARG" ;;
		c) MUTED_COLOR="$OPTARG" ;;
		i) AUDIO_INTERVAL="$OPTARG" ;;
		h) printf "help" ;;
	esac
done

function move_sinks_to_new_default {
	DEFAULT_SINK=$1
	pactl info | grep 'Default Sink' | while read SINK; do
		pactl set-default-sink $SINK
	done
}

function print_format {
	[[ $USE_PERCENT == 0 ]] && PERCENT=""
	case "$1" in
		1) echo "<span color=\"$ICON_COLOR\">$SYMBOL</span> $VOL$PERCENT" ;;
		2) echo "$SYMBOL$VOL$PERCENT";;
		3) echo "$SYMBOL$VOL$PERCENT" ;;
		*) echo "$SYMBOL$VOL$PERCENT" ;;
	esac
}

function print_block {
	for name in NAME; do
		read $name
	done < <(pactl info | grep 'Default Sink:')
	NAME=$(echo "$NAME" | awk '{print $3}')
	DESCRIPTION=$(pactl list sinks | grep -B2 -A1 "$NAME$" | grep Description | cut -f2- -d\ )
	INDEX=$(pactl list sinks | grep -B2 -A1 "$NAME$" | grep Sink | cut -f2 -d\#)

	#if [[ $USE_DESCRIPTION == 1 ]]; then
	#	NAME="$DESCRIPTION"
	#fi

	# Stupid but ok sure
	EXTRA_STUFF=""
	if [[ $BLOCK_BUTTON && ($BLOCK_BUTTON -eq 1 || $BLOCK_BUTTON -eq 3) ]]; then
		NAMES=($(pactl list short sinks | awk '{print $2}' | sort))

		# Find the index of the current sink in the NAMES array
		CURRENT_INDEX=-1
		for i in "${!NAMES[@]}"; do
			if [[ "${NAMES[i]}" == "$NAME" ]]; then
				CURRENT_INDEX=$i
				break
			fi
		done

		# switch to the next sink in the list or the first one if not found
		if [[ $CURRENT_INDEX -ge 0 ]]; then
			if [[ $BLOCK_BUTTON -eq 1 ]]; then
				NEXT_INDEX=$(( (CURRENT_INDEX + 1) % ${#NAMES[@]} ))
			else
				NEXT_INDEX=$(( (CURRENT_INDEX - 1 + ${#NAMES[@]}) % ${#NAMES[@]} ))
			fi
		else
			NEXT_INDEX=0
		fi

		NEXT_SINK="${NAMES[NEXT_INDEX]}"

		# Use pactl command to switch to the next sink
		pactl set-default-sink "$NEXT_SINK"
		EXTRA_STUFF=" [$NEXT_SINK]"
	fi

	[[ $USE_PERCENT == 1 ]] && VOL="$(pamixer --get-volume-human)" || VOL=$(pamixer --get-volume)

	MUTED=$(pamixer --get-mute)

	if [[ $MUTED =~ "false" ]] ; then
		SYMBOL=$AUDIO_HIGH_SYMBOL
		COLOR=$DEFAULT_COLOR
		[[ ${VOL/\%/} -ge $AUDIO_HIGHEST_THRESH ]] && COLOR=$AUDIO_HIGHEST_COLOR && ICON_COLOR=$AUDIO_HIGHEST_COLOR
		#[[ ${VOL/\%/} -gt $AUDIO_HIGHER_THRESH ]] && COLOR=$AUDIO_HIGHER_COLOR
		[[ ${VOL/\%/} -lt $AUDIO_MED_HIGH_THRESH ]] && SYMBOL=$AUDIO_MED_HIGH_SYMBOL
		[[ ${VOL/\%/} -lt $AUDIO_MED_THRESH ]] && SYMBOL=$AUDIO_MED_SYMBOL
		[[ ${VOL/\%/} -le $AUDIO_LOW_THRESH ]] && SYMBOL=$AUDIO_LOW_SYMBOL
	else
		SYMBOL=$AUDIO_MUTED_SYMBOL
		COLOR=$MUTED_COLOR
		ICON_COLOR=$MUTED_COLOR
	fi

	echo "<span color=\"$ICON_COLOR\">$SYMBOL</span> $VOL$PERCENT$EXTRA_STUFF"
	echo "<span color=\"$ICON_COLOR\">$SYMBOL</span> $VOL$PERCENT"
	echo "$COLOR"
}

print_block
